/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.almworks.sqlite4java;

/**
 * Although this class was not generated by SWIG, we'll keep the naming for convenience
 */
class SWIGTYPE_p_direct_buffer {
  private long swigCPtr;

  protected SWIGTYPE_p_direct_buffer(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_direct_buffer() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_direct_buffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}