#define WRAPPER_INVALID_ARG_1 (-11)
#define WRAPPER_INVALID_ARG_2 (-12)
#define WRAPPER_INVALID_ARG_3 (-13)
#define WRAPPER_INVALID_ARG_4 (-14)
#define WRAPPER_INVALID_ARG_5 (-15)

#define WRAPPER_CANNOT_TRANSFORM_STRING (-20)
#define WRAPPER_CANNOT_ALLOCATE_STRING (-21)

#define WRAPPER_WEIRD (-99)
#define WRAPPER_WEIRD_2 (-199)
